[package]
name = "bot"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
serenity = { version = "0.12.2", features = ["cache", "framework"] }
tokio = { version = "1.40.0", features = ["rt-multi-thread"] }
