[package]
name = "boris"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
rand = "0.8.5"
serenity = { version = "0.12.2", features = ["framework", "standard_framework"] }
tokio = { version = "1.40.0", features = ["rt-multi-thread", "signal"] }
